### ISSUE TITLE
Production-ready version of code

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/Focus_Locality_Extraction#2]
I wanted to know if there was an updated version of the code that's production ready, namely for situations when I have text and would like the focus location but don't have any labels. All the current code requires labels to be passed around. It must be running on XCEDE without labels so I thought I'd ask. 

Basically I want to give it a chunk of text (and MITIE output) and get back the place name string that it thinks is the focus location.

**Comment by Maryam-Imani** [comment]
I am working on that and will post it as soon as I complete and test it.

**Comment by Maryam-Imani** [comment]
> I wanted to know if there was an updated version of the code that's production ready, namely for situations when I have text and would like the focus location but don't have any labels. All the current code requires labels to be passed around. It must be running on XCEDE without labels so I thought I'd ask.
> 
> Basically I want to give it a chunk of text (and MITIE output) and get back the place name string that it thinks is the focus location.

I am working on that and will post it as soon as I complete and test it.

**Comment by ahalterman** [comment]
Now included in https://github.com/openeventdata/Focus_Locality_Extraction/tree/master/Focus_Locality/Sentence_Embedding_Approach/Testing
